# Generated by Django 5.0.7 on 2024-08-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
