# Generated by Django 5.0.7 on 2024-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(default='Descriptions'),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(default='location', max_length=100),
        ),
    ]
